const path = require( 'path' )
const express = require( 'express' )
const adminController = require( '../controllers/admin' )
const isAdmin = require( '../middleware/is-admin' )
const { Eventupload } = require( '../util/eventUpload' )
const router = express.Router()
router.get( '/add-event', isAdmin, adminController.getPostEvent )
router.get( '/edit-event/:eventId', isAdmin, adminController.getEditEvent )
// router.get('/event/:eventId',)
router.post( '/edit-event/:eventId', isAdmin, Eventupload.single( 'ImageEvent' ), adminController.postEditEvent )
router.post( '/add-event', isAdmin, Eventupload.single( 'ImageEvent' ), adminController.postPostEvent )
router.post( '/delete-event/:eventId', isAdmin, adminController.deleteEvent )
module.exports = router