const path = require( 'path' )
const express = require( 'express' )
const adminController = require( '../controllers/admin' )
const bahanController = require( '../controllers/bahan' )
const isAdmin = require( '../middleware/is-admin' )
const { Eventupload, Bahanupload } = require( '../util/eventUpload' )
const router = express.Router()
router.get( '/add-event', isAdmin, adminController.getPostEvent )
router.get( '/edit-event/:eventId', isAdmin, adminController.getEditEvent )
router.get( '/add-product', isAdmin, bahanController.getAddProduct )
router.post( '/add-product', isAdmin, Bahanupload.single( 'ImageBahan' ), bahanController.postAddProduct )
router.post( '/edit-event/:eventId', isAdmin, Eventupload.single( 'ImageEvent' ), adminController.postEditEvent )
router.post( '/add-event', isAdmin, Eventupload.single( 'ImageEvent' ), adminController.postPostEvent )
router.post( '/delete-bahan/:bahanId', isAdmin, bahanController.DeleteProduct )
router.post( '/delete-event/:eventId', isAdmin, adminController.deleteEvent )
module.exports = router